export const SET_USER = 'SET_USER';
export const SET_TOKEN = 'SET_TOKEN';
export const SET_PLAYLIST = 'SET_PLAYLIST';
export const SET_RECOMMENDED = 'SET_RECOMMENDED';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';
export const SET_RECENT_TRACKS = 'SET_RECENT_TRACKS';
export const SET_CURRENT_TRACK = 'SET_CURRENT_TRACK';
